### ISSUE TITLE
Parser Error on small float/double values 

### ISSUE THREAD

**Issue by tburschka** [creof/geo-parser#8]
Hello,

I've currently have an exception with the Lexer since 0.0000001 is internal represented as 1.0E-7 which is not valid for the Lexer. Maybe the lexer shoud use number_format on such strings to get the correct representation since the string "0.0000001" works fine.

**Steps to Reproduce:**
```
$pointDouble = new Point(0.0000001, 0);
$pointString = new Point("0.0000001", 0);
```

**System:**
PHP 7.0.5/XDEBUG 2.4.0/Debian 8.3 (If you familiar with vagrant you can use "ideaplexus/jessie64_symfony" box with that configuration)

**Comment by sadortun** [comment]
Hello @tburschka  

We have PR #7 on it's way that will fix this issue.

**Comment by sadortun** [comment]
Hello @tburschka   Issue is fixed in develop. If you see the problem again, please re-open this issue
